CNUOSS/CNU-SAM-BE

src/main/java/gp/cnusambe/config/WebSecurityConfig.java
src/main/java/gp/cnusambe/controller/UserController.java
src/main/java/gp/cnusambe/exception/ExceptionResolver.java
src/main/java/gp/cnusambe/exception/InvalidPasswordException.java
src/main/java/gp/cnusambe/exception/custom/AccessTokenException.java
src/main/java/gp/cnusambe/exception/custom/InvalidPasswordException.java
src/main/java/gp/cnusambe/exception/custom/RefreshTokenException.java
src/main/java/gp/cnusambe/exception/custom/UserIdDuplicatedException.java
src/main/java/gp/cnusambe/exception/custom/UserNotFoundException.java
src/main/java/gp/cnusambe/service/UserDetailsServiceImpl.java

- 로그아웃 버그 수정
- ExceptionResolver으로 커스텀 Exception 관리 기능 추가
#4

[#4] 로그아웃 버그 수정 및 Exception 관리 기능 추가

---

src/main/java/gp/cnusambe/config/CorsConfig.java
src/main/java/gp/cnusambe/config/WebSecurityConfig.java
src/main/java/gp/cnusambe/controller/UserController.java
src/main/java/gp/cnusambe/exception/ExceptionResolver.java
src/main/java/gp/cnusambe/exception/InvalidPasswordException.java
src/main/java/gp/cnusambe/exception/custom/AccessTokenException.java
src/main/java/gp/cnusambe/exception/custom/InvalidPasswordException.java
src/main/java/gp/cnusambe/exception/custom/RefreshTokenException.java
src/main/java/gp/cnusambe/exception/custom/UserIdDuplicatedException.java
src/main/java/gp/cnusambe/exception/custom/UserNotFoundException.java
src/main/java/gp/cnusambe/service/UserDetailsServiceImpl.java

CORS 정책 반영한 필터 추가

---

src/main/java/gp/cnusambe/controller/OssLicenseController.java
src/main/java/gp/cnusambe/domain/OssAnalysisMap.java
src/main/java/gp/cnusambe/repository/OssLicenseRepository.java
src/main/java/gp/cnusambe/service/OssLicenseService.java
src/test/java/gp/cnusambe/controller/OssLicenseControllerTest.java
src/test/java/gp/cnusambe/service/OssLicenseServiceTest.java

- OssLicenseName 데이터 보내기
- #28

[#28]3.4.1 License name Data

---

src/main/java/gp/cnusambe/controller/RestrictionController.java
src/main/java/gp/cnusambe/repository/RestrictionRepository.java
src/main/java/gp/cnusambe/service/RestrictionService.java

- RestrictionName 데이터 가져오는 API 구현
- #30

[#30]3.4.3 Restriction name Data

---

src/main/java/gp/cnusambe/controller/OssLicenseTypeController.java
src/main/java/gp/cnusambe/repository/OssLicenseTypeRepository.java
src/main/java/gp/cnusambe/service/OssLicenseTypeService.java

- OssLicenseType 데이터 가져오는 API 구현
- #31

[#31] 3.4.4 License Type name Data 가져오기

---

src/main/java/gp/cnusambe/controller/OssLicenseController.java
src/main/java/gp/cnusambe/controller/ProjectController.java
src/main/java/gp/cnusambe/controller/RestrictionController.java
src/main/java/gp/cnusambe/controller/VersionController.java
src/main/java/gp/cnusambe/domain/Project.java
src/main/java/gp/cnusambe/domain/ProjectCategory.java
src/main/java/gp/cnusambe/domain/Version.java
src/main/java/gp/cnusambe/dto/ProjectDto.java
src/main/java/gp/cnusambe/repository/ProjectCategoryRepository.java
src/main/java/gp/cnusambe/repository/ProjectRepository.java
src/main/java/gp/cnusambe/service/OssLicenseService.java
src/main/java/gp/cnusambe/service/ProjectService.java
src/test/java/gp/cnusambe/service/ProjectServiceTest.java

- Project 등록하기 구현
- 테스트 코드
- #35

[#35] 3.1.3 Project 등록하기

---

src/main/java/gp/cnusambe/controller/OssLicenseController.java
src/main/java/gp/cnusambe/controller/ProjectController.java
src/main/java/gp/cnusambe/controller/RestrictionController.java
src/main/java/gp/cnusambe/controller/SWController.java
src/main/java/gp/cnusambe/controller/VersionController.java
src/main/java/gp/cnusambe/domain/Department.java
src/main/java/gp/cnusambe/domain/LectureType.java
src/main/java/gp/cnusambe/domain/Project.java
src/main/java/gp/cnusambe/domain/ProjectCategory.java
src/main/java/gp/cnusambe/domain/Version.java
src/main/java/gp/cnusambe/dto/ProjectDto.java
src/main/java/gp/cnusambe/repository/DepartmentRepository.java
src/main/java/gp/cnusambe/repository/LectureTypeRepository.java
src/main/java/gp/cnusambe/repository/ProjectCategoryRepository.java
src/main/java/gp/cnusambe/repository/ProjectRepository.java
src/main/java/gp/cnusambe/repository/UserRepository.java
src/main/java/gp/cnusambe/service/OssLicenseService.java
src/main/java/gp/cnusambe/service/ProjectService.java
src/main/java/gp/cnusambe/service/SWService.java
src/test/java/gp/cnusambe/service/ProjectServiceTest.java

[#22] 2.2.8 이수구분 전체 조회

---

src/main/java/gp/cnusambe/service/OssLicenseService.java

- Restriction 없는 OssLicense 삭제시, OssLicense 삭제 안되는 오류 수정
- #27

[#27] OssLicense 삭제기능 오류 해결

---

src/main/java/gp/cnusambe/controller/LectureSWController.java
src/main/java/gp/cnusambe/controller/SubscriptionSWController.java
src/main/java/gp/cnusambe/domain/SubscriptionSW.java
src/main/java/gp/cnusambe/exception/custom/SWNotFoundException.java
src/main/java/gp/cnusambe/payload/request/SubscriptionSWRequest.java
src/main/java/gp/cnusambe/payload/response/SubscriptionSWResponse.java
src/main/java/gp/cnusambe/repository/SubscriptionSWRepository.java
src/main/java/gp/cnusambe/service/LectureSWService.java
src/main/java/gp/cnusambe/service/SubscriptionSWService.java

[#24] 구독 SW 등록

---

src/main/java/gp/cnusambe/controller/LectureSWController.java
src/main/java/gp/cnusambe/payload/response/DepartmentResponse.java
src/main/java/gp/cnusambe/payload/response/LectureTypeResponse.java
src/main/java/gp/cnusambe/service/LectureSWService.java

Domain에서 DTO로 데이터 타입 수정
#22 #23

[#22 #23] 이수 구분 & 조직 분류 전체 조회 : 데이터 타입 수정

---

src/main/java/gp/cnusambe/controller/RegisterSWController.java
src/main/java/gp/cnusambe/domain/Manufacturer.java
src/main/java/gp/cnusambe/payload/response/ManufacturerResponse.java
src/main/java/gp/cnusambe/repository/ManufacturerRepository.java
src/main/java/gp/cnusambe/service/RegisterSWService.java

[#21] 2.3.8 제조사 전체 조회

---

src/main/java/gp/cnusambe/controller/ProjectController.java
src/main/java/gp/cnusambe/payload/request/ProjectPostRequest.java
src/main/java/gp/cnusambe/payload/response/ProjectDetailResponse.java
src/main/java/gp/cnusambe/payload/response/ProjectPostResponse.java
src/main/java/gp/cnusambe/service/ProjectService.java

- Project 등록시에, ProjectDto를 projectPostRequest와 projectPostResponse로 변경하였다.
- #42

[#42] ProjectDto, OssLicenseDto -> Response, Request Dto로 변경하기

---

src/main/java/gp/cnusambe/controller/ProjectController.java
src/main/java/gp/cnusambe/domain/Project.java
src/main/java/gp/cnusambe/dto/ProjectDto.java
src/main/java/gp/cnusambe/payload/response/ProjectDetailResponse.java
src/main/java/gp/cnusambe/payload/response/VersionResponse.java
src/main/java/gp/cnusambe/repository/ProjectRepository.java
src/main/java/gp/cnusambe/repository/VersionRepository.java
src/main/java/gp/cnusambe/service/OssLicenseService.java
src/main/java/gp/cnusambe/service/ProjectService.java
src/test/java/gp/cnusambe/service/ProjectServiceTest.java

- 프로젝트 상세보기 기능 구현
- 테스트 코드 작성
- #45

[#45] 3.1.2 Project 상세보기 기능 구현

---

src/main/java/gp/cnusambe/controller/ProjectController.java
src/main/java/gp/cnusambe/service/ProjectService.java

[#47] 3.1.5 Project 삭제기능 구현

---

src/main/java/gp/cnusambe/controller/ProjectCategoryController.java
src/main/java/gp/cnusambe/service/ProjectCategoryService.java

- ProjectCategoryName 데이터 조회기능 구현
- #29

[#29] 3.4.2 Category name Data 조회기능 구현

---

src/main/java/gp/cnusambe/controller/OssLicenseController.java
src/main/java/gp/cnusambe/dto/PageInfoDto.java
src/main/java/gp/cnusambe/payload/response/MetaResponse.java
src/main/java/gp/cnusambe/payload/response/OssLicenseListResponse.java

- totalcount -> totalElemetns.
- isEnd -> last
- totalPages 변수 추가
- size 변수 추가
- #62

[#62] MetaResponse 변수명 변경 및 추가

---

src/main/java/gp/cnusambe/payload/request/ProjectPostRequest.java
src/test/java/gp/cnusambe/service/ProjectServiceTest.java

- Project 등록시, ProjectStatus "C"로 고정
- #64

[#64] Project 등록시 ProjectStatus -> "C"로 고정 

---

src/main/java/gp/cnusambe/payload/request/ProjectPostRequest.java
src/main/java/gp/cnusambe/repository/ProjectQueryRepository.java
src/test/java/gp/cnusambe/service/ProjectServiceTest.java

- Project List 조회 및 검색기능에서, licenseId 입력이 안되면, projectName, category, userId 반영 안되는 오류 수정
- #67

[#67] Project List 검색조건 반영 안되는 오류 수정

---

src/main/java/gp/cnusambe/controller/SubscriptionSWController.java
src/main/java/gp/cnusambe/domain/SubscriptionSW.java
src/main/java/gp/cnusambe/dto/SubscriptionSWDto.java
src/main/java/gp/cnusambe/payload/request/SubscriptionSWRequest.java
src/main/java/gp/cnusambe/payload/response/SubscriptionSWListResponse.java
src/main/java/gp/cnusambe/repository/SwSubscriptionQueryRepository.java
src/main/java/gp/cnusambe/service/SubscriptionSWService.java

- SubscriptionSW 기능에 DTO를 적용(마지막 두 개의 커밋만 확인해도 됩니다)
- ModelMapper 사용에 대해서 확인해주세용
#24  #25

[#24 #25] 전반적인 SubscriptionSW 기능에  SubscriptionSWDto 적용

---

src/main/java/gp/cnusambe/controller/RegistrationSWController.java
src/main/java/gp/cnusambe/domain/RegistrationSW.java
src/main/java/gp/cnusambe/payload/request/RegistrationSWRequest.java
src/main/java/gp/cnusambe/payload/response/RegistrationSWListResponse.java
src/main/java/gp/cnusambe/payload/response/SubscriptionSWListResponse.java
src/main/java/gp/cnusambe/repository/RegistrationSWQueryRepository.java
src/main/java/gp/cnusambe/repository/RegistrationSWRepository.java
src/main/java/gp/cnusambe/repository/SubscriptionSWQueryRepository.java
src/main/java/gp/cnusambe/service/RegistrationSWService.java
src/main/java/gp/cnusambe/service/SubscriptionSWService.java

- 수업 등록용 SW 전체 조회 및 검색
- 전체 SW 중 isManaged가 true 인 데이터만 반환
- false인 데이터는 이후 lectureSW 기능에서 처리함
- QueryRepository들 내부 함수가 겹치므로 나중 refactor에서는 공통적인 함수로 만들면 좋을 듯
#54

[#54] 2.3.2 수업 등록용 SW 전체 조회 및 검색

---

src/main/java/gp/cnusambe/controller/RegistrationSWController.java
src/main/java/gp/cnusambe/controller/SubscriptionSWController.java
src/main/java/gp/cnusambe/domain/RegistrationSW.java
src/main/java/gp/cnusambe/domain/SubscriptionSW.java
src/main/java/gp/cnusambe/dto/RegistrationSWDto.java
src/main/java/gp/cnusambe/service/RegistrationSWService.java
src/main/java/gp/cnusambe/service/SubscriptionSWService.java

- RegistrationSW과 SubscriptionSW
- Controller에서는 Request/Response를 사용
- Service에서는 Dto를 사용하도록 수정

SW : 계층에서 사용하는 데이터 구분하기

---

src/main/java/gp/cnusambe/controller/RegistrationSWController.java
src/main/java/gp/cnusambe/domain/RegistrationSW.java
src/main/java/gp/cnusambe/exception/ExceptionResolver.java
src/main/java/gp/cnusambe/service/RegistrationSWService.java

[#71] 2.3.5. 수업 등록용 SW 수정

---

src/main/java/gp/cnusambe/controller/ProjectController.java
src/test/java/gp/cnusambe/controller/OssLicenseControllerTest.java
src/test/java/gp/cnusambe/controller/ProjectControllerTest.java
src/test/java/gp/cnusambe/service/ProjectServiceTest.java

[#74] 3.1.5 Project 삭제 기능 구현

---

src/main/java/gp/cnusambe/config/AppConfig.java
src/main/java/gp/cnusambe/payload/request/ProjectPostRequest.java
src/main/java/gp/cnusambe/service/ProjectService.java

- 문자열인 user_id를 주어지면 project 등록이 안되는 오류 해결
- ModelMapper에 matchingstrategy 추가하는 StrictMapper 생성
- #82

[#82] 문자열인 user_id를 주어지면 project 등록이 안되는 오류 해결

---

src/main/java/gp/cnusambe/controller/LectureSWController.java
src/main/java/gp/cnusambe/domain/LectureMap.java
src/main/java/gp/cnusambe/domain/LectureSW.java
src/main/java/gp/cnusambe/domain/RegistrationSW.java
src/main/java/gp/cnusambe/domain/SWInLectureSW.java
src/main/java/gp/cnusambe/dto/LectureMapDto.java
src/main/java/gp/cnusambe/dto/LectureSWDto.java
src/main/java/gp/cnusambe/dto/SWInLectureSWDto.java
src/main/java/gp/cnusambe/payload/request/LectureSWRequest.java
src/main/java/gp/cnusambe/payload/response/LectureSWResponse.java
src/main/java/gp/cnusambe/repository/LectureMapRepository.java
src/main/java/gp/cnusambe/repository/LectureSWRepository.java
src/main/java/gp/cnusambe/repository/RegistrationSWRepository.java
src/main/java/gp/cnusambe/service/LectureSWService.java

- 수업 SW 등록 구현
- 수업 중에 사용하는 sw가 등록되어 있는지 여부에 따라서 분기가 갈림
- 등록되어 있지 않으면, ismanaged = false로 하여 registrationSW에 저장 
- 공통적으로 lectureSW와 lectureMapper 저장하고 생성 정보 반환
- 마지막 5개 커밋 만 봐주세요..^^
#56

[#56] 2.2.1 수업 SW 등록

---

src/main/java/gp/cnusambe/controller/LectureSWController.java
src/main/java/gp/cnusambe/repository/LectureMapRepository.java
src/main/java/gp/cnusambe/service/LectureSWService.java

[#59] 2.2.6 수업 SW 삭제

---

src/main/java/gp/cnusambe/controller/VersionController.java
src/main/java/gp/cnusambe/dto/AnalysisRestrictionDto.java
src/main/java/gp/cnusambe/dto/LicenseProtectorDto.java
src/main/java/gp/cnusambe/exception/custom/VersionNotFoundException.java
src/main/java/gp/cnusambe/payload/response/LicenseProtectorResponse.java
src/main/java/gp/cnusambe/service/VersionService.java
src/test/java/gp/cnusambe/service/VersionServiceTest.java

[#17] 3.2.2 라이선스 지킴이 상세보기

---

src/main/java/gp/cnusambe/controller/LectureSWController.java
src/main/java/gp/cnusambe/service/LectureSWService.java

2.2.4 수업 SW 상세 조회

---

src/main/java/gp/cnusambe/controller/LectureSWController.java
src/main/java/gp/cnusambe/dto/LectureSWForChartDto.java
src/main/java/gp/cnusambe/payload/response/LectureSWForChartResponse.java
src/main/java/gp/cnusambe/repository/LectureMapRepository.java
src/main/java/gp/cnusambe/repository/LectureSWRepository.java
src/main/java/gp/cnusambe/repository/RegistrationSWRepository.java
src/main/java/gp/cnusambe/service/LectureSWService.java

- 수업 SW 차트 조회
- 등록용 SW에 해당하는 SW(ismanaged=true)만 반영

2.2.7. 수업 SW 차트 조회

---

src/main/java/gp/cnusambe/controller/RegistrationSWController.java
src/main/java/gp/cnusambe/payload/response/SWNameResponse.java
src/main/java/gp/cnusambe/repository/RegistrationSWRepository.java
src/main/java/gp/cnusambe/service/RegistrationSWService.java

수업용 SW 등록을 위한 제품명 리스트 제공

---

src/main/java/gp/cnusambe/domain/LectureMap.java
src/main/java/gp/cnusambe/domain/LectureSW.java
src/main/java/gp/cnusambe/domain/LectureSWList.java
src/main/java/gp/cnusambe/domain/SWInLectureSW.java
src/main/java/gp/cnusambe/dto/SWInLectureSWDto.java
src/main/java/gp/cnusambe/service/LectureSWService.java

-  Add license as Column In LectureSW
- Plz, check just Last Commit 
- (ㅎㅏㄴㄱㅡㄹㅇㅣ ㅇㅣㅅㅏㅇㅎㅐ...)
#56 #57 #58

Add license as Column In LectureSW

---

src/main/java/gp/cnusambe/exception/custom/ProjectNotFoundException.java
src/main/java/gp/cnusambe/service/VersionService.java

- Version 등록시, ProjectStatus ->  "R"로 변경
- Version 삭제시, Project의 version이 존재하지 않을 경우 ProjectStatus -> "C" 로 변경
#91

[#91] Version 생성 및 삭제시, ProjectStatus 변경 기능 구현

---

src/main/java/gp/cnusambe/controller/LectureSWController.java
src/main/java/gp/cnusambe/controller/RegistrationSWController.java
src/main/java/gp/cnusambe/controller/SubscriptionSWController.java
src/main/java/gp/cnusambe/service/LectureSWService.java
src/main/java/gp/cnusambe/service/RegistrationSWService.java
src/main/java/gp/cnusambe/service/SubscriptionSWService.java

- Fix Id Mapping Error in SW
#95

Fix Id Mapping Error in SW

---

src/main/java/gp/cnusambe/controller/LectureSWController.java
src/main/java/gp/cnusambe/controller/RegistrationSWController.java
src/main/java/gp/cnusambe/controller/SubscriptionSWController.java
src/main/java/gp/cnusambe/domain/LectureSWList.java
src/main/java/gp/cnusambe/service/LectureSWService.java
src/main/java/gp/cnusambe/service/RegistrationSWService.java
src/main/java/gp/cnusambe/service/SubscriptionSWService.java

[fix] Add isManaged in LectureSW

---

.gitignore
Dockerfile
docker-compose.yml
src/main/resources/application.properties

Add Docker

---

Dockerfile
docker-compose.yml

Docker 관련 파일 이름 수정

---

.github/workflows/build-and-push-docker-image.yml

- main으로 push하거나, tag를 추가하면 docker hub에 배포
- docker hub에 fortune00/cnusam 으로 검색하면 볼 수 있음

build and push docker image

---

build.gradle
src/test/java/gp/cnusambe/controller/AbstractContainerBaseTest.java
src/test/java/gp/cnusambe/controller/OssLicenseControllerTest.java
src/test/java/gp/cnusambe/controller/ProjectControllerTest.java
src/test/java/gp/cnusambe/controller/UserControllerTest.java
src/test/resources/application.properties

테스트 컨테이너 적용

---

build.gradle
src/main/java/gp/cnusambe/controller/SubscriptionSWController.java
src/main/java/gp/cnusambe/domain/SubscriptionSW.java
src/main/java/gp/cnusambe/exception/custom/SWDuplicatedException.java
src/main/java/gp/cnusambe/payload/request/SubscriptionSWUpdateRequest.java
src/main/java/gp/cnusambe/repository/SubscriptionSWRepository.java
src/main/java/gp/cnusambe/service/SubscriptionSWService.java
src/test/java/gp/cnusambe/controller/AbstractContainerBaseTest.java
src/test/java/gp/cnusambe/controller/OssLicenseControllerTest.java
src/test/java/gp/cnusambe/controller/ProjectControllerTest.java
src/test/java/gp/cnusambe/controller/UserControllerTest.java
src/test/resources/application.properties

- 구독용 SW 수정 기능 추가
- 구독용 SW 관리 예외처리
- 리펙토링

구독용 SW 예외 처리, 수정 기능 추가, 그리고 리펙토링

---

src/main/java/gp/cnusambe/repository/domain/SubscriptionSW.java
src/test/java/gp/cnusambe/controller/SubscriptionSWControllerTest.java
src/test/java/gp/cnusambe/fixture/SubscriptionSWFixture.java

[#122] 구독용 SW 테스트 코드 작성

---

src/main/java/gp/cnusambe/repository/domain/LicenseRestrictionMap.java
src/main/java/gp/cnusambe/repository/domain/OssAnalysisMap.java
src/main/java/gp/cnusambe/repository/domain/OssLicense.java

1.LicenseRestrictionMap : restriction -> Cascade 중복 설정 
2.OssLicense : ossLicenseType -> Cascade 중복 설정
3.Version : project -> Cascade 중복 설정
4.Domain/OssAnalysisMap의 licenseTypeName의 length 10 -> 20으로 변경
#108, #50

[#108,#50] Refactor licenseRestricionMap,OssAnalysisMap, OssLicense

---

src/main/java/gp/cnusambe/repository/VersionRepository.java
src/main/java/gp/cnusambe/service/ProjectService.java

1. Project 상세보기에서 version들 최신 등록을 기준으로 정렬
#92

[#92] Project 상세보기에서 Version 정렬

---

src/main/java/gp/cnusambe/controller/OssLicenseController.java
src/main/java/gp/cnusambe/repository/RestrictionRepository.java
src/main/java/gp/cnusambe/repository/domain/AnalysisRestrictionMap.java
src/main/java/gp/cnusambe/repository/domain/LicenseProtect.java
src/main/java/gp/cnusambe/repository/domain/LicenseRestrictionMap.java
src/main/java/gp/cnusambe/repository/domain/Restriction.java
src/main/java/gp/cnusambe/service/OssLicenseService.java
src/main/resources/initdata/data.sql

1. Restriction 테이블에 id(pk), scope 필드 추가하기
2. Restrction 테이블 수정에 따라, datainit 수정하기
3. Restrction 테이블 수정에 따라, LicenseRestrictionMap, AnalysisRestrictionMap 수정함
4. Restrction 테이블 수정에 따라, 라이선스 등록하기 부분 수정
#60

[#60] Restriction 테이블 변경 및 라이선스 등록하기 수정
